# Generated by Django 4.1.7 on 2023-04-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
