# Generated by Django 4.2 on 2023-05-21 19:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
