# Generated by Django 4.2 on 2023-05-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
